title: We Don't Need Roads
description: This is the personal blog of Sam Chaffee. I'm a software engineering director with Open LMS. I have a background in GIS and an interest in open-source software and technology.
permalink: pretty
exclude: [README.md, CNAME, Gemfile, Gemfile.lock]
remote_theme: jekyll/minima
minima:
  skin: solarized-light
  social_links:
    - { platform: github,  user_url: "https://github.com/samchaffee" }
    - { platform: mastodon, user_url: "https://indieweb.social/@samchaffee" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/samchaffee" }
github_username: samchaffee
linkedin_username: samchaffee
mastodon:
  - username: samchaffee
    instance: indieweb.social
show_excerpts: true
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
